DROP TABLE IF EXISTS REGIAO CASCADE;

DROP TABLE IF EXISTS JOGADORES CASCADE;

DROP TABLE IF EXISTS JOGOS CASCADE;

DROP TABLE IF EXISTS CONVERSAS CASCADE;

DROP TABLE IF EXISTS MENSAGENS CASCADE;

DROP TABLE IF EXISTS NORMAL CASCADE;

drop table if exists MULTIJOGADOR cascade;

drop table if exists CRACHAS cascade;

drop table if exists JOGA_MJ cascade;

drop table if exists COMPRAR cascade;

drop table if exists ESTATISTICAS_JOGO cascade;

drop table if exists ESTATISTICAS_JOGADORES cascade;